@ProyectoDivine_HostAddress = https://ingenier-asoftwareayudant-as-3.onrender.com
POST {{ProyectoDivine_HostAddress}}/api/auth/
Content-Type: application/json

{
    "email": "admin@divine.cl",
    "password": "admin123"
}


###
