@ProyectoDivine_HostAddress = http://localhost:5258
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjEiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9lbWFpbGFkZHJlc3MiOiJhZG1pbkBkaXZpbmUuY2wiLCJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiRnJhbmNpc2NvMiAgVXNlciIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzc4ODIyODQ2LCJpc3MiOiJUZWF0cm9EaXZpbmUiLCJhdWQiOiJUZWF0cm9EaXZpbmUifQ.OKGPk_fN-nSvazqz-KT2D1ZHByY5S6XvlQq2QY-VK5Q
POST {{ProyectoDivine_HostAddress}}/api/auth/
Content-Type: application/json

{
    "email": "admin@divine.cl",
    "password": "admin123"
}


###
POST {{ProyectoDivine_HostAddress}}/api/Reservation/
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "funtionId": 1,
    "selectedSeats": [
        {
            "row": 1,
            "number": 1
        },
        {
            "row": 1,
            "number": 2
        }
    ]
}